### ISSUE TITLE
IAM Zero example fails if AWS region is `None`

### ISSUE THREAD

**Issue by chrnorm** [common-fate/iamzero-python-example#3]
Thanks to @jaydhulia for helping track down the issue.

Steps to reproduce:

- Delete ~/.aws/config file if you have it, or atleast delete the AWS_REGION part of it
- Unset env AWS_REGION if you have it set
- Just run the python example script and you will see the error
```
Traceback (most recent call last):
  File "/Users/Jay/personal/scratch/iamzero-python-example/env/lib/python3.9/site-packages/iamzero/instrumentation/botocore.py", line 7, in wrapped_api_call
    result = wrapped(*args, **kwargs)
  File "/Users/Jay/personal/scratch/iamzero-python-example/env/lib/python3.9/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/Users/Jay/personal/scratch/iamzero-python-example/env/lib/python3.9/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/Users/Jay/personal/scratch/iamzero-python-example/env/lib/python3.9/site-packages/botocore/validate.py", line 293, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter CreateBucketConfiguration.LocationConstraint, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

On using a debugger, this happens because this line below is returning None:
region = my_session.region_name

**Comment by chrnorm** [comment]
Closing - fixed in #4
